#!/bin/bash
#
# Copyright (C) 2024 nosignal

arch=`uname -m`
neko_dir="/etc/neko"
tmp_dir="/tmp"
log="$neko_dir/tmp/log.txt"

url_geo="https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest"

geoip_path="${neko_dir}/geoip.metadb"
geosite_path="${neko_dir}/geosite.db"
neko_bin="${neko_dir}/core/mihomo"

rpid=`pgrep "neko/core"`
if [[ -n $rpid ]] ; then
    kill $rpid 
fi

echo "[ `date +%T` ] - Checking Files"

files_check() {
    uci set uhttpd.main.index_page='index.php'
    uci set uhttpd.main.interpreter='.php=/usr/bin/php-cgi'
    uci commit uhttpd

    /etc/init.d/uhttpd restart
}
if [ -f "/tmp/neko/neko.bak" ]; then
    echo "[ `date +%T` ] - Old Files Detected"
    if [ -f "/tmp/neko/geoip.metadb" ]; then
        cp -rf "/tmp/neko/geoip.metadb" "/etc/neko/geoip.metadb"
    else
        echo "GeoIP Not Detected, Downloading"
        wget -q --no-check-certificate -O ${geoip_path} ${url_geo}/geoip.metadb
    fi

    if [ -f "/tmp/neko/geosite.db" ]; then
        cp -rf "/tmp/neko/geosite.db" "/etc/neko/geosite.db"
    else
        echo "GeoSite Not Detected, Downloading"
        wget -q --no-check-certificate -O ${neko_dir} ${url_geo}/geosite.db
    fi

    if [ -f "/tmp/neko/cache.db" ]; then
        cp -rf "/tmp/neko/cache.db" "/etc/neko/cache.db"
    else
        echo "Neko Cache Not Detected, Skipped"
    fi
    
    cp -rf /tmp/neko/config/* "/etc/neko/config/"
    cp -rf /tmp/neko/proxy_provider/* "/etc/neko/proxy_provider/"
    cp -rf /tmp/neko/rule_provider/* "/etc/neko/rule_provider/"
else
    echo "[ `date +%T` ] - Old Files Not Detected, Checking Files"
    files_check
fi

if [ $arch == "mips_24" ]; then
    sed -i "s/#wget/wget/g" /etc/neko/core/neko
fi

uci set neko.cfg.enabled='0'
uci commit neko
