#!/bin/bash

# Copyright (C) 2024 nosignal

neko_status=$(uci -q get neko.cfg.enabled)
neko_new_interface=$(uci -q get neko.cfg.new_interface)
neko_delay=$(uci -q get neko.cfg.delay)
tun_bin="/etc/neko/core/tun"
neko_pid="/etc/neko/tmp/neko_pid.txt"
log="/etc/neko/tmp/log.txt"
firewall="/etc/init.d/firewall"
neko_version=$1

neko_checknewver(){
    new_version=$(curl -m 5 -f -s https://raw.githubusercontent.com/nosignals/neko/luci-app-neko/neko_version)
    if [ $neko_version == $new_version ] || [ -z $new_version ]; then
        strversion="- Latest"
    else
        strversion="- New v.$new_version"
        if [ $1 == "log" ]; then
            echo "[ `date +%T` ] New Version detected. v.$new_version" >> $log

        fi
    fi
}

neko_reload(){
    echo "Checking New Interfaces."
    dt=`ubus call network.interface dump`
    len=`echo $dt | jq '.interface' | jq length`

    for (( i=0; i<$len; i++ ))
    do
        tmpdt=`echo $dt | jq ".interface[$i]"`
        status=`echo $tmpdt | jq '.up'`
        if [ $status = true ]; then
            iface=`echo $tmpdt | jq '.interface' | sed 's/"//g'`
            uptime=`echo $tmpdt | jq '.uptime'`

            if [[ ! -d "/tmp/iface" ]]; then
                echo "creating tmp dir"
                mkdir /tmp/iface
            fi
        
            if [ ! -e /tmp/iface/$iface ]; then
                echo $uptime > /tmp/iface/$iface
            fi
        
            last_uptime=`cat /tmp/iface/$iface`
            echo $uptime > /tmp/iface/$iface
            echo "- $iface Uptime $uptime s, last Uptime $last_uptime s"
        
            if (( $uptime < $last_uptime )) || [ -z $last_uptime ]; then
                echo "reloading firewall"
                echo "[ `date +%T` ] - Detected interfaces $iface changed, Reloading Firewall " >> $log
                $tun_bin -ks
            else
                echo "nothing"
            fi
        fi
    done
}

if [ "$neko_status" == 1 ] && [ "$neko_new_interface" == 1 ]; then
    echo "[ `date +%T` ] - Auto Restart Firewall : ON " >> $log
    sleep 20 && neko_checknewver "log"
    while true
    do
        sleep "$neko_delay"
        neko_reload
    done
else
    echo "[ `date +%T` ] - Auto Restart Firewall : OFF " >> $log
    sleep 20 && neko_checknewver "log"
fi